name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y g++ autoconf automake libtool build-essential pkg-config libc++-dev libgflags-dev libgtest-dev libpng-dev libjpeg8-dev libtiff5-dev zlib1g-dev libleptonica-dev git wget curl unzip libpthread-stubs0-dev
    - name: check out gRPC
      run: cd /usr/local/src && git clone --depth 1 --recursive https://github.com/grpc/grpc
    - name: build gRPC
      run: cd /usr/local/src/grpc && make && make DESTDIR=/usr/local install && cd /usr/local/src/grpc/third_party/protobuf && make install
    - name: check out tesseract
      run: cd /usr/local/src && wget https://github.com/tesseract-ocr/tesseract/archive/4.0.0.zip && unzip 4.0.0.zip
    - name: build tesseract
      run: cd /usr/local/src/tesseract-4.0.0 && ./autogen.sh && ./configure --prefix=/usr/local && make && make install
    - name: ldconfig
      run: ldconfig    
    - name: configure
      run: cd ~ && ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
